CREATE TABLE tb_product_category
(
    category_id BIGINT NOT NULL,
    product_id  BIGINT NOT NULL,
    CONSTRAINT pk_tb_product_category PRIMARY KEY (category_id, product_id)
);

CREATE TABLE tb_products
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    date        TIMESTAMP WITHOUT TIME ZONE,
    description TEXT,
    price       NUMERIC(38, 2),
    img_url     VARCHAR(255),
    CONSTRAINT pk_tb_products PRIMARY KEY (id)
);

ALTER TABLE tb_product_category
    ADD CONSTRAINT fk_tbprocat_on_category FOREIGN KEY (category_id) REFERENCES tb_categories (id);

ALTER TABLE tb_product_category
    ADD CONSTRAINT fk_tbprocat_on_product FOREIGN KEY (product_id) REFERENCES tb_products (id);