CREATE TABLE tb_roles
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    authority VARCHAR(255),
    CONSTRAINT pk_tb_roles PRIMARY KEY (id)
);

CREATE TABLE tb_user_role
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_tb_user_role PRIMARY KEY (role_id, user_id)
);

CREATE TABLE tb_users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    email      VARCHAR(255),
    password   VARCHAR(255),
    CONSTRAINT pk_tb_users PRIMARY KEY (id)
);

ALTER TABLE tb_user_role
    ADD CONSTRAINT fk_tbuserol_on_role FOREIGN KEY (role_id) REFERENCES tb_roles (id);

ALTER TABLE tb_user_role
    ADD CONSTRAINT fk_tbuserol_on_user FOREIGN KEY (user_id) REFERENCES tb_users (id);